# Generated by Django 5.0.1 on 2024-01-09 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
